language: node_js
node_js:
- lts
install:
- npm install
script:
- npm test
deploy:
  edge: true
  provider: npm
  email: bart@bartdorsey.com
  api_key:
    secure: m8QPyOKyW49rsdsOlDabqcrozMWPWo45QF8m0X/q/9kBxvwJ+O86lZfZ+vO/qgO1tl4clyruSjrjknpprQuqNfkCT0/d05hGLTukfwDsWbmz4Gr8kBpX/05IC5h06P+O9NNfQ64dKXAf7A+aIj6c5QgYYuskdkMeGFngAFLi+i+GTdT0Qzv77/6rKc7rpxufgmrlZmrlbGd8Wl4jyYebaQbgtivObU76wgzIwq0lnvfGkkCBECX8DW9d5jB2SwO9/T9LAWou/8oGSwZQOFBNhf4riLn7LrRJXa9yAtRDQOfN1tTu2sz4npIYOuVtW0y8Ahd4JV7eGBjVUs99j58awzqUhz+Rn6jMuoVWaaqkCUHHxiv0Dj3aCE6bgyexcdKhfXR+MLCkSuQB71UuRz3dX7a7iCsW7++zZ7mh3tn8EJ741i3Zp9CnsSYHnjH/MOm4X/ROy0f1Ws7HdjsprUbRw419aD3A4HtsEF0HoH9KUMTWtpfmPGYZlRhP2O5z9+wl7tp+amrczd6n/ydcri0EVEWVBuEjySRRWkjGxTvajDLlYfahO/rqj/EKMicXeCNyPg8zPD7X9d47lTrlrr0qz7VPqDvCXajjtdlIoxQremVckwstE1kuPSi2bgRJEP4REwoc1ozzwvjDvE9HAZzyR1mUD4VEOXEiR2/HWZTLsqY=
  on:
    tags: true
    repo: bartdorsey/homebridge-blinkcameras
